### PR TITLE
create user model and minor modifications

### PR DESCRIPTION
**Pull request by eldrego**
#### What does this PR do?
Create User Model
#### Description of Task to be completed?
User model should have necessary field
- Username
- Password

#### More context
- I pulled @jidemobell initial feature as it had not been merged and I need some startup file there.
- I renamed the app.js file to read index.js - Considering we will be implementing the application using es6, this name change will come in handy when transpiling.
- I populated the gitignore file
- create user model
- changed eslint config to use airbnb
- added npm scripts to start app in cmd line - `npm run dev`

### CODE REVIEW

**Comment by eldrego** [comment]
[user model](https://trello.com/c/eXjzZvlx/34-user-model)

**Comment by eldrego** [comment]
Good observation. How should the UserModel be structure then? Are we able to ascertain what fields are redundant and the ones that are necessary?

**Comment by jidemobell** [comment]
I guess "**fullname**" may not be required, _email_ to double as username

**Comment by jidemobell** [comment]
and I haven't learnt so much of mongoose (hooks) . A requirement we have to create social media strategies, each strategy (when passed) can check if the user already exist or create one if not.

**Comment by eldrego** [comment]
For Social  media strategies, I believe we can work on that as part of the create-user/register/signup feature

**Pull request merged**
